[search] : 결과 route bar 넣기 레이아웃 (#76)
makchamakers/makchata pull request #80
Opened 2023-11-26 16:08 UTC by dlsxody1

## 🚩 이슈 번호
- close #76 

## 📝 작업 내용
- 이동수단 소요시간에 따른 route bar를 만들었습니다.
![image](https://github.com/makchamakers/makchata/assets/62875596/8e691c91-1644-4981-9f62-32aa57ce1193)

- 막차시간 부분은 서버 작업이 완료되면 추가 해놓도록 하겠습니다.

## 📣 리뷰 요청사항/알릴사항/질문
[알릴사항] 저번에 말씀드렸던 스피너도 추가 해놓도록 하겠습니다!

2023-11-28 14:06 UTC, eun0leee commented on src/components/search/Button/ChipButton.tsx
> +import { MyHomeSVG } from '../assets';
다른 모듈 import시 절대경로로 불러오고 있으므로 절대경로를 사용하면 어떨까요?

2023-11-28 14:07 UTC, eun0leee commented on src/components/search/Button/CurrentLocationButton.tsx
> +import CurrentLocationIcon from '../assets/CurrentLocationIcon';
assets 부분만 상대경로로 돼있는데, 절대경로로 사용하면 어떨까요?

2023-11-28 14:09 UTC, eun0leee commented on src/components/search/Button/CurrentLocationButton.tsx
> +    </>
이미 button tag로 하나의 루트엘리먼트로 반환하고 있는데, 빈태그가 필요한가용??

2023-11-28 14:09 UTC, eun0leee commented on src/components/search/Input.tsx
> +    </>
여기도 빈태그가 필요한가용??

2023-11-28 14:13 UTC, eun0leee commented on src/components/search/Input.tsx
> +      />
type attribute가 없습니다!

2023-11-28 14:25 UTC, eun0leee commented on src/components/search/Input.tsx
> +        value={inputType === 'arrival' ? search.arrival : search.departure}
input.tsx 안에서 e.target 은 구조분해가 돼있는데, debounceValue와 search는 그대로 쓰셔서 여쭤봅니당
다른 코드에서 map의 콜백함수의 첫번째 파라미터도 구조분해하여 썼던 것 같은데

구조분해하는 까를로스만의 기준이 혹시 있다면 어떤건지 궁금합니다..! 👀

2023-11-28 14:31 UTC, eun0leee commented on src/components/search/Button/CurrentLocationButton.tsx
> +  right: 5%;
- 현재버튼이 오른쪽으로부터 패딩 안으로 완전히 들어와야하는데, 들어오지 못한 것 같습니다!
- 그리고 상하 패딩값이 수정돼야할 것 같은데 확인 부탁드립니다!

로컬 브라우저 캡쳐
![스크린샷 2023-11-28 오후 11 29 06](https://github.com/makchamakers/makchata/assets/90189513/3661309b-ffc4-481e-802f-bec4d84d6fef)
figma 캡쳐
![스크린샷 2023-11-28 오후 11 29 14](https://github.com/makchamakers/makchata/assets/90189513/27f02afd-7eb4-428c-87bc-c176cc654404)

2023-11-28 14:36 UTC, eun0leee commented on src/api/api.ts
>      `${process.env.NEXT_PUBLIC_SERVER_BASE_URL}/destination?sx=${sx}&sy=${sy}&ex=${ex}&ey=${ey}`
utils/apis/path.ts 내에 있는 getPathLists 함수로 사용해주셔야할 것 같아요!

2023-11-28 14:53 UTC, eun0leee commented on src/components/search/ResultCard.tsx
> +`;
styled 전용 props라는 뜻으로 앞에 `$`를 붙여줘야 에러가 나지 않더라고요!
#58 pr의 [bug : alarm prop 앞에 $ 붙임](https://github.com/makchamakers/makchata/issues/55) 커밋 참고 부탁드립니다 :)

2023-11-28 14:57 UTC, eun0leee commented on src/components/search/ResultCard.tsx
>      <Link prefetch={false} href={`/route/${index.toString()}`}>
이렇게 prefetch 를 설정해줄 수 있군요..!! 서버상에서 api 요청이 많이 일어나는 저희에겐 꼭 필요했던 기능이네요😂

2023-11-28 15:11 UTC, eun0leee commented on src/type/search.ts
>  export interface IResultProps {
에러잡느라 고생 많으셨습니다 :)

2023-11-28 15:11 UTC, eun0leee commented on src/type/path.ts
> +  ey: string;
이 부분이 string으로 들어가야 했었군요! 수정 감사합니다 :)

2023-11-28 15:21 UTC, eun0leee commented
까를로스 정말 많은 작업하시느라 고생 많으셨습니다! 😃

그리고 부탁드리고 싶은게 있는데요! merge와 코드리뷰가 바로바로 이뤄지지 않는 점이 문제점이지만.. ㅠㅠ  이전 pr merge가 안됐더라도 이슈단위별로 새로 pr 생성해주신다면 코드 보기가 더 편할 것 같습니다!

Reviewers 지정 부탁드리고, projects는 issue 에서만 선택하면 좋을 것 같아요! issue 에서도 선택하고 pr 에서도 선택하면 같은 내용이 projects에 중복돼 반영돼 작업사항을 한눈에 보기 힘들 것 같아요

2023-11-28 15:23 UTC, eun0leee requested changes
까를로스 정말 많은 작업하시느라 고생 많으셨습니다! 😃

그리고 부탁드리고 싶은게 있는데요! merge와 코드리뷰가 바로바로 이뤄지지 않는 점이 문제점이지만.. ㅠㅠ  이전 pr merge가 안됐더라도 이슈단위별로 새로 pr 생성해주신다면 코드 보기가 더 편할 것 같습니다! `feat : 회의 때 나왔던 데이터 수정, 출발시간 계산 함수 개발` 코드는 아직 보지 못해서 내일 더 보도록 하겠습니다ㅎㅎ

Reviewers 지정 부탁드리고, projects는 issue 에서만 선택하면 좋을 것 같아요! issue 에서도 선택하고 pr 에서도 선택하면 같은 내용이 projects에 중복돼 반영돼 작업사항을 한눈에 보기 힘들 것 같아요!

2023-11-28 15:23 UTC, eun0leee requested changes
까를로스 정말 많은 작업하시느라 고생 많으셨습니다! 😃

그리고 부탁드리고 싶은게 있는데요! merge와 코드리뷰가 바로바로 이뤄지지 않는 점이 문제점이지만.. ㅠㅠ  이전 pr merge가 안됐더라도 이슈단위별로 새로 pr 생성해주신다면 코드 보기가 더 편할 것 같습니다! `feat : 회의 때 나왔던 데이터 수정, 출발시간 계산 함수 개발` 코드는 아직 보지 못해서 내일 더 보도록 하겠습니다ㅎㅎ

Reviewers 지정 부탁드리고, projects는 issue 에서만 선택하면 좋을 것 같아요! issue 에서도 선택하고 pr 에서도 선택하면 같은 내용이 projects에 중복돼 반영돼 작업사항을 한눈에 보기 힘들 것 같아요!

2023-11-29 09:10 UTC, dlsxody1 commented on src/components/search/index.ts
> +export { default as ChipButton } from './Button/ChipButton';
import { sum } from './utils/index';

import { sum } from './utils';

일단 index.ts를 사용하면 위처럼 축약이 가능해서 엠마가 처음에 만들어 놓은 것 같아요 
예전에 흐릿하게 기억나는데 index라는 파일 자체를 우선순위로 찾아서 ...(그 이후는 잘 기억이..) 이점이 있다는 것 같은데
자세히는 모르겠네요..?!  

assets 폴더는 저는 처음 스프린트 때 여기 있었던 것을 사용해서 어디에 있어야 하는지 생각하지 못했네요
옮겨 놓을게요!

2023-11-29 09:11 UTC, dlsxody1 commented on src/components/search/assets/CurrentLocationIcon.tsx
> +import React from 'react';
rsc 라는 커맨드로 컴포넌트를 만들어서 자동적으로 생긴 녀석이네요..
필요없는 것들은 지우도록 할게요!

2023-11-29 09:13 UTC, dlsxody1 commented on src/components/search/Button/CurrentLocationButton.tsx
> +import CurrentLocationIcon from '../assets/CurrentLocationIcon';
search 폴더 안에 assets가 있어서 그렇습니다! assets 폴더 옮겨 놓도록 할게요!

2023-11-29 09:13 UTC, dlsxody1 commented on src/components/search/Button/CurrentLocationButton.tsx
> +    </>
불필요한 fragment 자제 하도록 하겠습니다..

2023-11-29 09:15 UTC, dlsxody1 commented on src/components/search/Input.tsx
> +      />
추가 해 놓을게요!

2023-11-29 09:18 UTC, dlsxody1 commented on src/components/search/Input.tsx
> +        value={inputType === 'arrival' ? search.arrival : search.departure}
e.target은 input 관련 onChange 함수를 만들 때 습관적으로 구조분해할당 하는 것 같고,
저는 개인적으로는 안에  프로퍼티가 많으면 구조분해할당 합니다!
props.a , props.b , props.....  너무 많으면 props를 쓰기 귀찮아서요

2023-11-29 09:19 UTC, dlsxody1 commented on src/components/search/Button/CurrentLocationButton.tsx
> +  right: 5%;
앗 재빨리 수정하도록 하겠습니다

2023-11-29 09:19 UTC, dlsxody1 commented on src/components/search/ResultCard.tsx
> +`;
전에 봤었던 건데 깜빡했군요.. 수정해놓을게요!

2023-11-29 09:31 UTC, dlsxody1 commented on src/components/search/ResultCard.tsx
>      <Link prefetch={false} href={`/route/${index.toString()}`}>
Link 태그의 default가 true여서 prefetch되는 컴포넌트가 많을수록 비효율적이라고 생각해서 넣어봤습니다!
근데 hover 이벤트가 발생할 때 prefetch가 일어나서 prefetch를 아예 비활성화 하려면 
`
import { useRouter } from 'next/router';

function CustomLink({ href, children }) {
  const router = useRouter();

  const handleClick = (event) => {
    event.preventDefault();
    router.push(href);
  };

  return (
    <a href={href} onClick={handleClick}>
      {children}
    </a>
  );
}

export default CustomLink;
`
이런식으로 사용해봐야할 것 같아요! 
좀 더 효율적인 방식을 찾아볼게요!

2023-11-29 09:33 UTC, dlsxody1 commented
일일히 체크해주셔서 감사합니다..! 자꾸 놓치는 부분이 있네요
앞으로는 꼼꼼히 체크해서 이슈 단위 별로 올려볼게요 감사합니다!

2023-11-30 09:47 UTC, dlsxody1 reviewed
불필요한 fragment, svg 다운로드 , property 이름 변경 완료하였습니다

2023-11-30 11:41 UTC, eun0leee commented on src/components/search/index.ts
> +export { default as ChipButton } from './Button/ChipButton';
아하 이전에 작업돼있던 거군요..!
저도 리뷰하면서 이렇게 쓰는거랑 public에서 쓰는 거랑 어떤 차이가 있는지 찾아보니까 
public 에 담아두고, next/image 사용해서 가져오면 아래와 같은 기능을 제공한다고 하네요!
nextjs 사용하게 됐으니 제공하는 기능들을 최대한 사용해보면 좋을 것 같아요!

- lazy loading
- 이미지 사이즈 최적화
- placeholder 제공

[Next/Image를 활용한 이미지 최적화](https://fe-developers.kakaoent.com/2022/220714-next-image/)
[Nextjs 공식문서 image](https://nextjs.org/docs/pages/api-reference/components/image)

2023-11-30 11:43 UTC, eun0leee commented on src/components/search/Input.tsx
> +        value={inputType === 'arrival' ? search.arrival : search.departure}
아하! 적정개수 이상이 넘어가면 구조분해할당을 하시는군요..!
저도 저 나름의 기준을 세워봐야겠습니다..
까를로스 덕분에 다시 생각해보게되네요! 알려주셔서 감사합니다

2023-11-30 11:45 UTC, eun0leee commented on src/components/search/ResultCard.tsx
>      <Link prefetch={false} href={`/route/${index.toString()}`}>
아하! Link 말고 다른 방법을 쓰면 prefetch가 안되는군요..! 
오.. 자세히 알려주셔서 감사합니다

2023-11-30 11:53 UTC, wlsud801 approved these changes
녕녕이 꼼꼼하게 리뷰 잘해주셔서 저는 추가할 부분은 없네용 ㅎㅎ 수고하셨습니당

2023-11-30 11:53 UTC, merged